Netsuite:
  ACCOUNTID : "![tDzVtze2z3qn3pw9Ps/fiQ==]"
  CONSUMERKEY : "![9SO/y1K6EktIU3lI3gBnV2BqRdwyTOEL2Iy+rsl1jRczv15mnbkL48wQsNpv0lw8NFRlmytadFmxpijfbZe+nVJAHJyXyE63BSIkkxAXQ4g=]"
  CONSUMERSECRET : "![NImKCm2JNyha0GuBb740/tesO1qwpe0wSn6KjTScrvYy0/gPdEwgpYaa4iwWR4E+EIFDnNeVCAgX7gGnxVKVrkmzd5oaHcZzm4S8gZ9zga0=]"
  TOKENID : "![1uSnJT/d7qHh6nLESvXdiG3YgdHhIg1zIGLD8iwVa3DrZIS47MLM8kRxZHjsO9Op7jYPxl9HIYwatSJm23rOaKd89ScFuVUVduGl4tUGs/4=]"
  TOKENSECRET : "![Z2HdKZTGlswxEmKlqNs6IwdhnBugNlM5UjoCvDg7+4QMcjie6oWMjljWJXXeRUruYipYBtck4eYy7qYXTJoMilHlGsWOmmvcS8YUHa1C0S8=]"